export const IconInstanceName = {
  Eye: "Eye",
  EyeCrossOut: "EyeCrossOut",
  Menu: "Menu",
  CollapseMenu: "CollapseMenu",
  Sun: "Sun",
  Moon: "Moon",
  Cross: "Cross",
  Chevron: "Chevron",
  User: "User",
  LogOut: "LogOut",
  Feed: "Feed",
  Like: "Like",
  Dislike: "Dislike",
  ChevronWithLine: "ChevronWithLine",
  Sort: "Sort",
  SortDesc: "SortDesc",
  DeleteRounded: "DeleteRounded",
  ChevronSmall: "ChevronSmall",
} as const;

export const IconAppName = {
  ShowPassword: "ShowPassword",
  HidePassword: "HidePassword",
  Menu: "Menu",
  CollapseMenu: "CollapseMenu",
  Sun: "Sun",
  Moon: "Moon",
  Cross: "Cross",
  ChevronRight: "ChevronRight",
  User: "User",
  LogOut: "LogOut",
  Feed: "Feed",
  Like: "Like",
  Dislike: "Dislike",
  ChevronDown: "ChevronDown",
  ChevronLeft: "ChevronLeft",
  ChevronWithLineRight: "ChevronWithLineRight",
  ChevronWithLineLeft: "ChevronWithLineLeft",
  Sort: "Sort",
  SortDesc: "SortDesc",
  SortAsc: "SortAsc",
  ClearInput: "ClearInput",
  ChevronSmallDown: "ChevronSmallDown",
} as const;
