export const IconInstanceName = {
  Eye: "Eye",
  Menu: "Menu",
  CollapseMenu: "CollapseMenu",
  Sun: "Sun",
  Moon: "Moon",
  Cross: "Cross",
  Chevron: "Chevron",
  User: "User",
  LogOut: "LogOut",
  Feed: "Feed",
  Like: "Like",
  Dislike: "Dislike",
} as const;

export const IconAppName = {
  ShowPassword: "ShowPassword",
  Menu: "Menu",
  CollapseMenu: "CollapseMenu",
  Sun: "Sun",
  Moon: "Moon",
  Cross: "Cross",
  ChevronRight: "ChevronRight",
  User: "User",
  LogOut: "LogOut",
  Feed: "Feed",
  Like: "Like",
  Dislike: "Dislike",
  ChevronDown: "ChevronDown",
} as const;
